opendatahub-io/distributed-workloads

- Quick-Start.md
- README.md
First Draft of a quick start guide to using the codeflare stack with open data hub.
> Quick Start draft 0.0.1

- Quick-Start.md
- codeflare-stack-kfdef.yaml
- codeflare-stack/base/codeflare-notebook-imagestream.yaml
- codeflare-stack/base/instascale.yaml
- codeflare-stack/base/kustomization.yaml
- codeflare-stack/base/mcad.yaml
- codeflare-stack/base/params.env
- codeflare-stack/base/params.yaml
- codeflare-stack/rbac/kustomization.yaml
- codeflare-stack/rbac/mcad-controller-ray-clusterrole.yaml
- codeflare-stack/rbac/mcad-controller-ray-clusterrolebinding.yaml
> Update quickstart instructions to account for CodeFlare operator

- codeflare-stack/base/codeflare-notebook-imagestream.yaml
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Automatically update codeflare image

- tests/basictests/distributed-workloads.sh
- tests/resources/codeflare-subscription.yaml
- util
Will run tests on my local machine
Depends on #21
> CodeFlare Installation test

- tests/basictests/distributed-workloads.sh
- tests/resources/custom-nb-small.yaml
- tests/resources/mcad.ipynb
- tests/resources/odh-subscriptoin.yaml
> Add notebook cr template

- tests/README.md
Add ODH deployment to the Prerequisites and instructions to deploy quickly.
> Add opendatahub deployment to the Prerequisites

- tests/README.md
- tests/resources/odh-subscription.yaml
Fix typeO in the test README.
Add odh-subscription.yaml file with the right spelling.
> Fix typeo in the test README

- Quick-Start.md
We previously linked only to the NDF and GPU operator repos. This adds a link to instructions to actually set them up.
> Add link to instructions for setting up GPU operator

- ray/operator/base/kustomization.yaml
closes https://github.com/opendatahub-io/distributed-workloads/issues/45
See discussion in issue
In my OSIA cluster I updated my kuberay operator version to v0.5.0 and the used the `codeflare-sdk` to create a new cluster and made sure that all functions such as `cluster.up()`, `cluster.wait_ready(), etc. worked.
> update ray operator image

- ray/operator/base/kustomization.yaml
- ray/operator/base/params.yaml
- ray/operator/scc/kustomization.yaml
- ray/operator/scc/ray_operator_scc.yaml
fixes: https://github.com/project-codeflare/codeflare-sdk/issues/129
I tested this on my local cluster by explicitly creating the SCC, I will retest after completely removing kuberay
> add scc that forces ray pods to run as user 1000

- tests/basictests/distributed-workloads.sh
Closes Issue #40 
Tested on Mac and Ubuntu with following steps:
0. Install jq, go, readlink binaries if not available on your mac and linux.
1. Login
`oc login --token=<your token> --server=https://api.jim4122.cp.fyre.ibm.com:6443`
2. Install codeflare operator, ODH operator, ODH core, and CodeFlare stack:
https://github.com/opendatahub-io/distributed-workloads/tree/main/tests#prerequisites
2. Setup testing harness:
```bash
git clone https://github.com/opendatahub-io/peak
git clone --single-branch --branch Improve-mac-e2e-test  https://github.com/tedhtchang/distributed-workloads.git
cd peak
git submodule update --init
echo distributed-workloads nil ../distributed-workloads  Improve-mac-e2e-test > my-list
./setup.sh -t my-list
```
4. Run e2e testing:
```bash …
```
> Allow Mac to run e2e test

- ray/operator/base/kustomization.yaml
- ray/operator/base/params.env
- ray/operator/base/params.yaml
- ray/operator/manager/manager.yaml
Refer to https://github.com/opendatahub-io/odh-manifests/pull/899 for additional context
> Add images as variables in params.yaml for Ray

- Quick-Start.md
- README.md
- tests/resources/codeflare-subscription.yaml
- tests/resources/mnist_ray_mini.ipynb
cc @tedhtchang @jbusche @sutaakar 
I will create a tag + release after this is merged.
> Distributed Workloads v0.1.0 release

- .github/workflows/build_tests.yml
Implemented a PR check GitHub workflow which will make sure that go files in `tests` folder can be compiled and are formatted.
Fixes https://github.com/opendatahub-io/distributed-workloads/issues/76
Tested on own fork by adjusting existing go test file to fail formatting check and creating a PR with this change. PR check failed, referring to this formatting issue.
> PR GitHub workflow validating go files in test folder

- OWNERS
Provide OWNERS file for OpenShift CI
This file is specifying users with approving rights for PRs in this repository. This file is used by OpenShift CI to detect if a PR in this repository can be merged.
N/A
> Provide OWNERS file for OpenShift CI

- Makefile
> Minor typo "Deleteing" to "Deleting"

- .github/workflows/tag-and-release.yml
Right now replacement command is replacing only text which match version regex. The replacement should replace any value to accommodate usage of dev image.
By manually running the workflow on own fork.
> Release workflow: Replace any image tag in codeflare-notebook-imagestream.yaml

- Quick-Start.md
Have a little more detail on install, cleanup and updated some of the notebook examples steps to match the current notebook demo.
- [ x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x ] The developer has manually tested the changes and verified that the changes work
> Updating and adding more install detail into QuickStart

- codeflare-stack/base/codeflare-notebook-imagestream.yaml
Latest release workflow incorrectly modifies CodeFlare ImageStream, overriding fields which weren't intended to be changed. This PR reverts the changes. Fix for workflow will follow.
Revert unintended CodeFlare ImageStream changes.
N/A
> Revert incorrect changes in CodeFlare ImageStream

- .github/workflows/tag-and-release.yml
Fixing release workflow as the previous version incorrectly replaced values in ImageStream.
Previous approach using sed wasn't flexible enough, as it replaced also lines which should stay fixed. This approach using yq replaces only specified lines.
Manually.
Tested using own repo fork, sample run is available on https://github.com/sutaakar/distributed-workloads/actions/runs/6158299771/job/16710778825, sample PR https://github.com/sutaakar/distributed-workloads/pull/9.
> Use yq to modify the codeflare-notebook-imagestream.yaml for release

- Quick-Start-ODH-V2.md
- README.md
- codeflare-dsc.yaml
closes: https://github.com/project-codeflare/codeflare-operator/issues/254
I walked through the steps and made sure that all the pods that should come up did.
> add new document for v2 quickstart

- Quick-Start-ODH-V2.md
- Quick-Start.md
- README.md
> Update documentation based on new operator design

- tests/basictests/distributed-workloads.sh
- tests/basictests/ray.sh
- tests/resources/codeflare-subscription.yaml
- tests/resources/custom-nb-small.yaml
- tests/resources/mnist_ray_mini.ipynb
Backport changes in ODH manifest tests
Backporting changes done to make manifest PR checks green - https://github.com/opendatahub-io/odh-manifests/pull/937
in manifest PR check
> Backport changes in ODH manifest tests

- codeflare-dsc.yaml
The example dsc no longer work for [quick start odh-v2](https://github.com/tedhtchang/distributed-workloads/blob/bf0737cbcc01aa17176b07173195e4e5061217a1/Quick-Start-ODH-V2.md?plain=1#L62)
> Update example-dsc dsc yaml for ohd v2 quickstart

- contrib/configuration/basic-dsc.yaml
Update DataScienceCluster used in OpenShift CI with placeholders to reference URI to PRs.
Manually by deploying the DSC to the latest ODH operator.
> Update DataScienceCluster for PR checks with manifest URI references

- tests/kfto/kfto_kueue_sft_test.go
Add integration test making sure that PytorchJob is suspended until there is free capacity in ClusterQueue.
Tested manually by running `go test -timeout 60m ./tests/kfto/` against OCP cluster with Kueue and Training operator deployed as part of ODH 2.11.0
> Add test coverage for sequential admission of PytorchJob

- tests/kfto/environment.go
Needed for disconnected cluster to properly mirror the image.
> Use SHA tag for model image

- tests/kfto/core/environment.go
- tests/kfto/core/kfto_kueue_sft_test.go
- tests/kfto/upgrade/kfto_kueue_sft_upgrade_test.go
Remove default fms-hf-tuning image to avoid accidental testing with different image than anticipated. 
Manually
> Remove default fms-hf-tuning image

- tests/kfto/core/kfto_kueue_sft_GPU_test.go
- tests/kfto/core/kfto_kueue_sft_test.go
Adjust  fms-hf-tuning training job security context to make sure it works as non root user with read only root filesystem.
Training job needs access to temp folder and huggingface home directory - mounted `/tmp` for this purpose.
Manually by running tests against OCP cluster.
> Set security context for fms-hf-tuning training job

- go.mod
- go.sum
- tests/kfto/core/kfto_kueue_sft_GPU_test.go
Enhancing `TestMultiGpuPytorchjobWithSFTtrainer` with a check verifying that there are two GPUs in the OpenShift cluster. Those GPUs should be utilized for at least 90% by multi GPU test.
> Adjust Training operator GPU test with GPU utilization verification

- README.md
- tests/kfto/core/kfto_kueue_sft_GPU_test.go
Adding NVidia GPU requests and limits for training pod to assure that it will be placed in correct node.
> Add GPU requests and limits for Training operator multiGPU test

- README.md
- tests/odh/environment.go
- tests/odh/mnist_ray_test.go
- tests/odh/notebook.go
- tests/odh/resources/custom-nb-small.yaml
- tests/odh/resources/mnist.py
- tests/odh/resources/mnist_ray_mini.ipynb
- tests/odh/resources/requirements.txt
- tests/odh/support.go
- tests/odh/template.go
As part of test reconciliation I am moving TestMnistRay from https://github.com/project-codeflare/integration-tests here. That way all the integration tests for DW stack are in one place.
> Move TestMnistRay from integration tests repo to ODH DW repo

- .github/workflows/odh-release.yml
Add odh test in odh-release workflow
> Add odh test in odh-release workflow

- OWNERS
> Remove Anish from reviewers

- go.mod
- go.sum
- tests/kfto/core/config_granite_20b_code_instruct.json
- tests/kfto/core/config_llama2_13b.json
- tests/kfto/core/config_meta_llama3_70b_instruct_lora.json
- tests/kfto/core/config_meta_llama3_8b_instruct.json
- tests/kfto/core/config_mixtral_8x7b_instruct_v01.json
- tests/kfto/core/environment.go
- tests/kfto/core/kfto_kueue_sft_GPU_test.go
Add multiGPU finetuning tests for granite, llama and mixtral models.
> Add multiGPU finetuning tests for granite, llama and mixtral models

- tests/kfto/core/config_merlinite_7b.json
- tests/kfto/core/kfto_kueue_sft_GPU_test.go
Add full finetuning of model ibm/merlinite-7b using Training operator.
> Add full finetuning for ibm/merlinite-7b

- tests/kfto/core/config_lora.json
- tests/kfto/core/kfto_kueue_sft_test.go
Added a sample test verifying LoRA training for Training operator.
This sample use small model and dataset to be able to run the tests in non GPU environment.
Also did some minor adjustments in existing finetuning test to align it with other tests in the repository.
Manually
> Add LoRA sample test for Training operator

- examples/ray-finetune-llm-deepspeed/README.md
> fix: Remove erroneous trailing double quote

- examples/stable-diffusion-dreambooth/README.md
Add in Kueue description in the SD Readme
Improved the `README.md` with Kueue description.
Looked through the readme.
> Add in Kueue description in the SD README

- tests/odh/mnist_raytune_hpo_test.go
- tests/odh/resources/hpo_raytune_requirements.txt
- tests/odh/resources/mnist_hpo.py
- tests/odh/resources/mnist_hpo_raytune.ipynb
- tests/odh/support.go
closes https://issues.redhat.com/browse/RHOAIENG-10004
- Added Test TestMnistRayTuneHpo to cover the functionality of HyperParameter Optimisation with Ray Tune with Ray image using codeflare-sdk stack
- Took reference of mnist HPO supported script for tuning here https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch.py 
go test -timeout 10m -v ./tests/odh -run TestMnistRayTuneHpo
> Add e2e Test for HyperParameter Optimisation with Ray Tune

- tests/kfto/core/config_meta_llama3_1_8b.json
- tests/kfto/core/config_mixtral_8x7b_v01.json
- tests/kfto/core/kfto_kueue_sft_GPU_test.go
Adding new models for testing, raising timeout to improve test stability.
Manually
> Minor adjustments for Training operator test scenarios

- tests/kfto/core/config.json
- tests/kfto/core/config_granite_20b_code_instruct.json
- tests/kfto/core/config_granite_34b_code_instruct_lora.json
- tests/kfto/core/config_llama2_13b_chat_hf.json
- tests/kfto/core/config_llama2_13b_chat_hf_lora.json
- tests/kfto/core/config_lora.json
- tests/kfto/core/config_merlinite_7b.json
- tests/kfto/core/config_meta_llama3_1_70b_lora.json
- tests/kfto/core/config_meta_llama3_1_8b.json
- tests/kfto/core/config_meta_llama3_70b_instruct_lora.json
- tests/kfto/core/config_meta_llama3_8b_instruct.json
- tests/kfto/core/config_mixtral_8x7b_instruct_v01.json
- tests/kfto/core/config_mixtral_8x7b_v01.json
- tests/kfto/core/kfto_kueue_sft_GPU_test.go
Adding meta-llama/Meta-Llama-3.1-70B model for test coverage
Removing deprecated parameter.
Manually
> Misc adjustments for Training operator tests

- .snyk
Added a [.snyk file ](https://docs.snyk.io/manage-risk/policies/the-.snyk-file#how-to-create-the-.snyk-file) to ignore the `examples` and `tests` directories from "Snyk code analysis".
I've enabled an option through the Snyk UI to exclude these directories, but they can only be excluded for "dependency analysis". There isn't an option in the UI to exclude from "code analysis" but can be achieved by using the `.snyk` file.
The need for this is that we are getting false positives on CVEs on files from the `examples` directory which are not used in production. This can be seen here: https://app.snyk.io/org/red-hat-openshift-data-science-rhods/project/dfa1938b-e57a-4448-abdc-8f3962460a43 
Moreover, Jiras are being created through automation:
https://issues.redhat.com/browse/RHOAIENG-10506
1. …
> Add .snyk config file to ignore examples and tests directories from snyk scans

- tests/kfto/core/environment.go
- tests/kfto/upgrade/kfto_sft_upgrade_sleep_test.go
Reference `gcr.io/k8s-staging-perf-tests/sleep` image using digest to be able to provide the image in disconnected environment.
Manually by running sleep test against OCP.
> Use sleep image referenced by digest for upgrade test

- go.mod
- go.sum
- tests/odh/mnist_ray_test.go
- tests/odh/mnist_raytune_hpo_test.go
- tests/odh/ray_finetune_llm_deepspeed_test.go
Fixed ODH e2e tests polling logic by returning error as part of return statement
Manually
> Fix polling logic by returning error as part of return statement

- examples/ray-finetune-llm-deepspeed/README.md
> Add Llama 3.1 8B fine-tuning on AMD MI300X GPUs validated config

- README.md
- examples/hpo-raytune/notebook/raytune-oai-MR-gRPC-demo.ipynb
- examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
- examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
- images/runtime/examples/ray-torch-cuda/Dockerfile
- images/runtime/examples/ray-torch-rocm/Dockerfile
[RHOAIENG-12186](https://issues.redhat.com/browse/RHOAIENG-12186)
Upgrading Ray version to 2.35.0 to allow for AMD GPU support.
Tested by running through the raytune-oai-demo.ipynb example using the new ray version/image, as well as the interactive_demo notebook in codeflare-sdk via this [PR](https://github.com/project-codeflare/codeflare-sdk/pull/666).
> Upgrade Ray to version 2.35.0

- examples/hpo-raytune/notebook/raytune-oai-MR-gRPC-demo.ipynb
- examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
- examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
- examples/stable-diffusion-dreambooth/notebook/raycluster.yaml
Updating examples in line with codeflare-sdk changes, issues found when testing for [RHOAIENG-12186](https://issues.redhat.com/browse/RHOAIENG-12186)
> Updating examples in line with codeflare-sdk changes

- tests/kfto/upgrade/kfto_kueue_sft_upgrade_training_test.go
Some time ago I updated Training operator tests to make them more reliable for downstream execution. I forgot to upgrade also upgrade tests to reflect same changes.
Here I port the changes to upgrade tests.
Manually by running upgrade tests against OCP cluster.
> Adjust upgrade test to align with other tests

- tests/kfto/core/config_mistral_7b_v03.json
- tests/kfto/core/config_mixtral_8x7b_instruct_v01_lora.json
- tests/kfto/core/kfto_kueue_sft_GPU_test.go
Changing TestMultiGpuPytorchjobMixtral8x7bInstructv01 to LoRa test, adding coverage for `mistralai/Mistral-7B-v0.3`
Manually against GPU OCP cluster.
> Adjust Training operator GPU tests

- go.mod
- go.sum
- tests/odh/mnist_ray_test.go
- tests/odh/mnist_raytune_hpo_test.go
- tests/odh/ray_finetune_llm_deepspeed_test.go
- tests/odh/support.go
Adjust integration tests to use updated Ray cluster client.
By running the affected tests against OCP cluster.
> Adjust integration tests to updated Ray cluster client

- images/runtime/examples/ray-torch-rocm/Dockerfile
Upgrade DeepSpeed in the example Ray container image for ROCm as it fixes build issues.
> Upgrade DeepSpeed to 0.15.1 to fix build with ROCm

- images/runtime/examples/ray-torch-rocm/Dockerfile
Tested Llama 3.1 8B fine-tuning on AMD MI300X accelerators successfully.
> Add gfx90a and gfx941 architectures to custom Ray ROCm image

- tests/kfto/core/config_qlora.json
- tests/kfto/core/kfto_kueue_sft_test.go
Providing proper model and parameters to test QLoRA.
Pre-requisite : NVidia A100/ Ampere based GPUs 
Tested manually  using image `quay.io/modh/fms-hf-tuning@sha256:12fda9b689848ffa8cbfb39a11597cdab1fbb93ddba83b5347987db90c1122a3`
> Adjust Training operator QLoRA test with working configuration

- .tekton/ray-cuda-push.yaml
- .tekton/ray-rocm-push.yaml
- README.md
- images/runtime/examples/ray-torch-cuda/Dockerfile
- images/runtime/examples/ray-torch-rocm/Dockerfile
- images/runtime/ray/cuda/Dockerfile
- images/runtime/ray/rocm/Dockerfile
[RHOAIENG-11843](https://issues.redhat.com/browse/RHOAIENG-11843)
Updating python version to 3.11 for Ray CUDA and Ray ROCm images
> Update python version to 3.11 for CUDA and ROCm images

- README.md
- go.mod
- go.sum
- images/util/mc-cli/Dockerfile
- tests/kfto/core/config.json
- tests/kfto/core/config_lora.json
- tests/kfto/core/config_qlora.json
- tests/kfto/core/environment.go
- tests/kfto/core/kfto_kueue_sft_GPU_test.go
- tests/kfto/core/kfto_kueue_sft_test.go
- tests/kfto/core/support.go
Add optional possibility to upload models trained using Training operator into s3 bucket.
Such models can be then reused by other components like serving.
Manually by running kfto tests against OCP cluster, uploading trained models into AWS s3 bucket.
> Upload models trained using Training operator into s3 bucket

- tests/kfto/core/kfto_kueue_sft_GPU_test.go
- tests/kfto/core/kfto_kueue_sft_test.go
Add Triton env variables to point misc folders to a scratch volume.
Adjust timeout for longer QLoRA test execution in base test.
Manually by running against OCP cluster.
> Adjust Training operator tests for latest QLoRA changes

- instructlab/standalone/README.md
- instructlab/standalone/standalone.py
Updating standalone.py with the latest changes from phase-1. It contains bug fixes and supporting for self-signed certificates for the Judge model if needed during the evaluation phase.
The instructlab `standalone.py` script has been update to address a couple of bug fixes and support for self-signed certificates for the judge model during the evaluation phase if needed.
Two additional environment variables are needed to pass the judge model CA cert. The script expects the CA to be mounted from a configmap
- JUDGE_SERVING_CA_CONFIGMAP_NAME
- JUDGE_SERVING_CA_CONFIGMAP_KEY
> Update instructlab standalone.py script 

- images/runtime/training/cuda/Dockerfile
- images/runtime/training/cuda/LICENSE.md
- images/runtime/training/rocm/Dockerfile
- images/runtime/training/rocm/LICENSE.md
[RHOAIENG-15034](https://issues.redhat.com/browse/RHOAIENG-15034)
Adding relevant licenses to the CUDA and ROCm training images as required by Konflux.
> Adding licenses to training images

- tests/odh/ilab_dw_rhoai_test.go
Create Judge model Secret based on information provided in environment variables.
User doesn't have to manually create Secret with all the needed values.
Environment variables used for Secret creation:
- `JUDGE_API_KEY`: Provide API key for Judge model endpoint
- `JUDGE_NAME`: Name of the Judge model
- `JUDGE_ENDPOINT`: Judge model serving endpoint
- `JUDGE_CA_CERT_FROM_OPENSHIFT`: flag indicating that Judge model endpoint use the same certificate as OpenShift CA where the script is running (so that the certificate should be trusted), set to `true`
Manually by running the test against OpenShift cluster with Judge model deployed in the same cluster.
> Dynamically create Judge model Secret resource

- go.mod
- go.sum
Update codeflare-common dependancy to latest
> Update codeflare-common dependancy 

- images/runtime/training/cuda/Dockerfile
- images/runtime/training/rocm/Dockerfile
Related to [RHOAIENG-15034](https://issues.redhat.com/browse/RHOAIENG-15034)
The following errors have been encountered in Konflux builds for the CUDA and ROCm Training images. 
```
[check-container]             {
[check-container]                 "name": "RunAsNonRoot",
[check-container]                 "elapsed_time": 0,
[check-container]                 "description": "Checking if container runs as the root user because a container that does not specify a non-root user will fail the automatic certification, and will be subject to a manual review before the container can be approved for publication",
[check-container]                 "help": "Check RunAsNonRoot encountered an error. Please review the preflight.log file for more information.",
[check-container] …
```
> Updating training images for konflux build

- tests/kfto/core/kfto_kueue_sft_GPU_test.go
- tests/kfto/core/kfto_kueue_sft_test.go
- tests/kfto/core/kfto_pytorchjob_failed_test.go
- tests/kfto/core/kfto_training_test.go
- tests/kfto/core/support.go
- tests/kfto/upgrade/kfto_kueue_sft_upgrade_training_test.go
- tests/kfto/upgrade/kfto_sft_upgrade_sleep_test.go
https://issues.redhat.com/browse/RHOAIENG-14542
> Add test coverage for error handling with PyTorchJob

- go.mod
- go.sum
- tests/kfto/core/environment.go
- tests/kfto/core/kfto_pytorchjob_failed_test.go
- tests/kfto/core/kfto_training_test.go
- tests/kfto/core/support.go
Add "ReadExt" method and update KFTO tests
This PR adds support for "ReadExt" method which helped in extracting the python training script in go test binaries. 
Also updated the KFTO tests to use the environment variable from codeflare-common repository
Tested the changes manually by running the KFTO test locally
> Add "ReadExt" method and update KFTO tests

- tests/kfto/core/kfto_kueue_sft_test.go
Add gpu resource to ClusterQueue
Tested manually by running cmd `go test -timeout 30m -v ./tests/kfto/core -run TestPytorchjobUsingKueueQuota`
> Add gpu resource to ClusterQueue

- tests/kfto/core/kfto_training_test.go
Remove volume which is not needed.
Remove duplicit environment variables.
Manually by running on OCP cluster.
> Remove duplicities in kfto_training_test.go

- tests/kfto/core/kfto_pytorchjob_failed_test.go
Removed config data and volumes from pytorch error handling as it's not used in the test
> Remove config data and volumes from pytorch error handling

- tests/kfto/upgrade/kfto_kueue_sft_upgrade_training_test.go
Create output volume for Training operator upgrade test.
This change was done in sanity tests, was missing in upgrade test.
> Fix Training operator upgrade test

- tests/kfto/core/kfto_training_test.go
Reduce memory requirement for pytorch job
Tested by executing the tests locally with NVIDIA and AMD gpu
> Reduce memory requirement for pytorch job

- .github/workflows/odh-release.yml
Update paths in odh-release workflow
Update paths for compiling tests in odh-release workflow
> Update paths in odh-release workflow

- examples/stable-diffusion-dreambooth/README.md
- examples/stable-diffusion-dreambooth/notebook/00 Intro.ipynb
- examples/stable-diffusion-dreambooth/notebook/01 raytrain-stablediffusion.ipynb
- examples/stable-diffusion-dreambooth/yaml/distributed/git-clone.yaml
- examples/stable-diffusion-dreambooth/yaml/distributed/workbench.yaml
- examples/stable-diffusion-dreambooth/yaml/operators/nfd-cr.yaml
Stable Diffusion example was referring to the old CodeFlare, the example wasn't running properly in newest RHOAI.
This PR upgrades the example to work with latest RHOAI/CodeFlare release.
Manually by running Stable Diffusion example against OSD cluster.
> Upgrade Stable Diffusion example to newest CodeFlare version

- tests/odh/validating_admission_policy_test.go
* Increased timeouts to 10 seconds 
* Added eventually to flaky "RayCluster should be admitted without the 'kueue.x-k8s.io/queue-name' label in any other namespace" test
* Added test namespace over "default" for tests that require a namespace without a Kueue label.
Tests have been run on a 4.17 cluster with RHOAI 2.17 nightly including the VAP.
`go test -v -timeout 1m ./tests/odh/validating_admission_policy_test.go ./tests/odh/support.go`
> fix: flaky vap test

- tests/kfto/kfto_mnist_training_test.go
Update KFTO multinode pytorch training test for disconnected
```
export AWS_SECRET_ACCESS_KEY=<>\
AWS_STORAGE_BUCKET=<> \
AWS_DEFAULT_REGION=us-east-1 \
AWS_DEFAULT_ENDPOINT=<> \
PIP_INDEX_URL=<> \
PIP_TRUSTED_HOST=<> \
AWS_STORAGE_BUCKET_MNIST_DIR=mnist-datasets \
CODEFLARE_TEST_TRAINING_IMAGE=quay.io/modh/training@sha256:b98e373a972ff6f896a9dc054d56920e915675339c02ea7fa123e0f4bbef4d74
```
```
go test  -timeout 45m -v ./tests/kfto -run TestPyTorchJobMnistMultiNodeSingleCpu
```
OutputLogFiles : 
[kfto-mnist-bq9pg-master-0-pytorch.log](https://github.com/user-attachments/files/18600775/kfto-mnist-bq9pg-master-0-pytorch.log)
[kfto-mnist-bq9pg-worker-0-pytorch.log](https://github.com/user-attachments/files/18600774/kfto-mnist-bq9pg-worker-0-pytorch.log) …
> Update KFTO multinode pytorch training test for disconnected

- tests/kfto/kfto_training_test.go
Declaring worker replicas separately, if worker replica is declared with number of pods 0 then Training operator keeps creating and deleting worker pods, causing tests to fail randomly.
Manually by running against OCP cluster.
> Specify Worker replicas in PyTorchJob only for existing workers

- tests/kfto/kfto_mnist_training_test.go
- While using 2*g4dn.xlarge GPUs, the prometheus metric's GPU usage value shows min 20%
- While using A100 GPUS this usage percentage becomes negligible
- Skipping GPU usage validation because the Multi-node tests are expected to run with high end Gpus (in case of MUlti-GPU scenarios) where the training consumes negligible percentage of GPUs
> Skip GPU usage validation for kfto pytorch multi-node tests

- examples/ray-finetune-llm-deepspeed/ray_finetune_llm_deepspeed.ipynb
Remove the hard-coded namespace from the RayCluster configuration in the LLM fine-tuning example so it uses that of the notebook.
> Remove hard-coded namespace Ray cluster configuration

- examples/ray-finetune-llm-deepspeed/ray_finetune_llm_deepspeed.ipynb
Update the LLM fune-tuning example to be compatible with the latest version of the CodeFlare SDK.
> Update Codeflare SDK imports in LLM fine-tuning Ray example

- examples/ray-finetune-llm-deepspeed/ray_finetune_llm_deepspeed.ipynb
Use PVC storage by default and set `HF_HOME` environment variable for shared caching.
> Use PVC storage by default and set HF_HOME for shared caching

- workshops/llm-fine-tuning/README.md
- workshops/llm-fine-tuning/kueue/local_queue.yaml
- workshops/llm-fine-tuning/kueue/resource_flavor.yaml
- workshops/llm-fine-tuning/kueue/team1_cq.yaml
- workshops/llm-fine-tuning/kueue/team2_cq.yaml
- workshops/llm-fine-tuning/nfs/nfs_deployment.yaml
- workshops/llm-fine-tuning/nfs/nfs_storage_class.yaml
Add LLM fine-tuning with Ray and Kueue workshop
> Add LLM fine-tuning with Ray and Kueue workshop

- workshops/llm-fine-tuning/README.md
- workshops/llm-fine-tuning/kfto/config.yaml
- workshops/llm-fine-tuning/kfto/job.yaml
- workshops/llm-fine-tuning/kfto/sft.py
Add KFTO section in LLM fine-tuning workshop
> Add KFTO section in LLM fine-tuning workshop

- images/runtime/training/cuda/Dockerfile
- images/runtime/training/rocm/Dockerfile
Fix the group permissions for the working directory so users can install and upgrade Python packages.
> Fix permissions in KFTO training images

- tests/fms/environment.go
- tests/kfto/environment.go
- tests/kfto/kfto_kueue_mnist_upgrade_training_test.go
- tests/kfto/kfto_upgrade_sleep_test.go
This PR move upgrade tests to kfto folder and adjust them to run with mnist script and KFTO image
Manually by running upgrade tests on OCP
> Move upgrade tests to kfto folder and adjust them to run with mnist script and KFTO image

- images/runtime/training/cuda/Dockerfile
Built and pushed at `quay.io/astefanu/training:py311-cuda121-torch241-fa27`, and successfully tested with #326.
> Add Flash Attention to CUDA training image

- tests/kfto/kfto_kueue_mnist_upgrade_training_test.go
Update KFTO_upgrade tests to run in disconnected environment
Manually by running upgrade tests in disconnected cluster
> Update KFTO_upgrade tests to run in disconnected environment

- tests/fms/resources/config_allam_beta_13b_chat_gptq.json
- tests/fms/resources/config_granite_34b_code_base_gptq.json
- tests/fms/resources/config_granite_8b_code_instruct_gptq.json
- tests/fms/resources/config_meta_llama3_1_405b_gptq.json
- tests/fms/resources/config_meta_llama3_70b_instruct_gptq_blue.json
- tests/fms/resources/config_mistral_7b_v03_gptq.json
- tests/fms/resources/config_mixtral_8x7b_instruct_v01_gptq.json
> Adjust QLoRA model path for fms-hf-tuning tests

- images/runtime/training/rocm/Dockerfile
> Fix missing line break in ROCm Dockerfile

- images/runtime/training/cuda/Pipfile
- images/runtime/training/cuda/Pipfile.lock
- images/runtime/training/rocm/Pipfile
- images/runtime/training/rocm/Pipfile.lock
Add bitsandbytes package to training images
> Add bitsandbytes to training images

- tests/kfto/kfto_kueue_mnist_upgrade_training_test.go
This change will lower the resource requirements for running upgrade tests.
> Use only one Pod for KFTO upgrade test

- tests/kfto/resources/hf_llm_training.py
[RHOAIENG-18862 
](https://issues.redhat.com/browse/RHOAIENG-18862)
As part of the current TensorBoard PoC the hf_llm_training.py script has been updated to show the addition of custom metrics logging via TensorBoard.
This should not be merged until after TensorBoard has been added to the training images via [RHOAIENG-17133](https://issues.redhat.com/browse/RHOAIENG-17133). The E2Es using this script will break without this change.
This has been tested manually on my ROSA cluster.
> Updating test training script to use tensorboard and custom metrics

- tests/kfto/resources/hf_llm_training.py
Related to [RHOAIENG-18862](https://issues.redhat.com/browse/RHOAIENG-18862)
Reverted recent TensorBoard metrics additions to hf_llm_training.py as RWX access to storage is not currently supported for E2E tests. Will use the TensorBoard related work done here in an example instead.
> Revert tensorboard updates to test training script

- images/runtime/training/cuda/Dockerfile
Add Infiniband and RDMA packages to KFTO CUDA image
> Add Infiniband and RDMA packages to KFTO CUDA image

- images/runtime/training/cuda/Dockerfile
- images/runtime/training/rocm/Dockerfile
> Use latest Python image base for Training runtime images

- images/runtime/training/cuda/Dockerfile
Add libibumad3 and mlnx-tools packages to KFTO CUDA image.
Successfully tested the LLM fine-tuning example with RoCE:
> Add libibumad3 and mlnx-tools packages to KFTO CUDA image

- go.mod
- go.sum
- tests/kfto/kfto_mnist_training_test.go
- tests/kfto/support.go
Use accelerator function from codeflare-common
NA
> Use accelerator function from codeflare-common

- images/runtime/training/cuda/Dockerfile
This upgrades the NCCL version that's transitively installed with torch to a more recent version.
Successfully tested the KFTO LLM fine-tuning example.
> Upgrade NCCL to 2.26.2 in Kubeflow CUDA training image

- OWNERS
Adding myself to OWNERS file for approval and review
> add laurafitzgerald to owners and approvers

- README.md
- tests/common/environment.go
- tests/common/test_tag.go
- tests/kfto/kfto_kueue_mnist_upgrade_training_test.go
- tests/kfto/kfto_mnist_sdk_test.go
- tests/kfto/kfto_mnist_training_test.go
- tests/kfto/kfto_pytorchjob_failed_test.go
- tests/kfto/kfto_training_test.go
- tests/kfto/kfto_upgrade_sleep_test.go
Run KFTO tests only if (test tier equals test tier env variable if defined) AND OpenShift environment match test requirements.
This is the base of work for running ODH e2e tests using image, providing all the configuration using env variables.
Manually by running e2e tests against various OCP environments.
> Implement custom test tags for ODH KFTO tests

- tests/kfto/kfto_mnist_training_test.go
- tests/kfto/kfto_training_test.go
Mouth /dev/shm into memory to avoid running out of shared memory in ROCm e2e tests.
> Mouth /dev/shm into memory

- Makefile
- images/tests/Dockerfile
Will be used for automated test image upgrade.
> Create Makefile command to generate test images for distributed-workloads

- README.md
- tests/common/environment.go
Useful for cases when using env variables is not possible or convenient.
Manually by running test image with test tier parameter:
```
podman run --rm   -v ./results:/distributed-workloads/tests/results:Z -v /home/<user>/.kube/config:/distributed-workloads/tests/.kube/config:Z quay.io/opendatahub/distributed-workloads-tests:latest --junitfile results/results.xml -- ./kfto -testTier=Sanity
```
> Add possibility to provide test tier using go lang parameter

- tests/kfto/kfto_mnist_sdk_test.go
- tests/kfto/kfto_mnist_training_test.go
- tests/kfto/kfto_pytorchjob_failed_test.go
- tests/kfto/kfto_training_test.go
- tests/kfto/kfto_upgrade_sleep_test.go
- tests/kfto/resources/mnist_kfto.ipynb
```
export NOTEBOOK_IMAGE=quay.io/modh/odh-generic-data-science-notebook@sha256:1c585c849cc466fce6443f5c186fb9b642d21b5f3581515ada08bba2fbc3591f \
TEST_TRAINING_IMAGE=quay.io/modh/training@sha256:1d0caea3e5d56ff7d672954b1ad511e661df9bdb364d56879961169a4ca8dae0 # CUDA
go test  -timeout 45m -v ./tests/kfto -run TestMnistSDK 
```
> Adjust existing kfto e2e tests to use kueue

- .github/workflows/build-and-push-test-images.yml
- images/tests/Dockerfile
Declare images used for tests in Dockerfile as env variables.
> Specify default test images as env variables in Dockerfile

- examples/kfto_feast_rag/README.md
- examples/kfto_feast_rag/feast_rag_retriever.py
- examples/kfto_feast_rag/feature_repo/feature_store.yaml
- examples/kfto_feast_rag/feature_repo/ragproject_repo.py
- examples/kfto_feast_rag/rag_feast_kfto.ipynb
[RHOAIENG-25280](https://issues.redhat.com/browse/RHOAIENG-25280)
As part of the collaborative POC for end-to-end RAG with Feast Feature Store, Kubeflow Trainer and RHOAI UI, we aimed to implement a custom FeastRagRetriever based on the RagRetriever class from Hugging Face Transformers.
In this PR, I’ve included a working example that demonstrates the proposed FeastRagRetriever implementation. This includes all necessary requirements for using Feast, a demo Jupyter notebook, and the relevant class definitions—providing a complete setup to showcase and run the integration.
**Note** - for this implementation we use a remote Milvus instance deployed on OpenShift.
In order to run `feast apply` successfully please install feast from the current master branch.
I have added a new directory under …
> Example using FeastRagRetriever implementation

- tests/kfto/kfto_mnist_training_test.go
Replaced value with function for test.Eventually check.
> Fix failing KueueWorkloads check

- README.md
- images/tests/Dockerfile
- tests/common/environment.go
- tests/kfto/kfto_mnist_sdk_test.go
- tests/kfto/resources/mnist_kfto.ipynb
Adjusted the test to retrieve user token dynamically in test based on credentials.
Small adjustments to leverage `papermill` parameters.
> Adjust KFTO MNIST SDK tests for shift left

- tests/kfto/validating_admission_policy_test.go
Added eventually polling logic to wait for the changes made in VAP and pytorchjob resource to be ready/available.
> Fix KFTO Kueue-VAP test
