Quick-Start.md

Fix an mcad installation error
Add missing `--set` flag
Add the `--set` flag and verify the `Error: "helm upgrade" requires 2 arguments` goes away and verified message below:
```
NAME: mcad
LAST DEPLOYED: Mon Feb  6 16:44:29 2023
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

Fix helm command to install MCAD

---

tests/README.md
tests/basictests/distributed-workloads.sh
tests/resources/test_mcad_ray.py
tests/util

This PR adds a testing template we can use to build our e2e tests for the distributed workloads/CodeFlare Stack.
* The template includes an empty function for each of the test issues we outlined on our [issues](https://github.com/opendatahub-io/distributed-workloads/issues) page. But feel free to supplement with more supporting functions if needed. 
* I added a small subset of tests for the KubeRay operator to get us started and provide an example of how to write tests in this format. 
* There is also a `resources` directory where we can add whatever scripts, yaml files, etc we will need during testing. It is currently just populated with template python file.

Add testing template

---

tests/basictests/distributed-workloads.sh

This solves E2E Step6 "Uninstall CodeFlare Operator" https://github.com/opendatahub-io/distributed-workloads/issues/20 
It goes hand and hand with the code written in Kevin's PR https://github.com/opendatahub-io/distributed-workloads/pull/22 
It essentially 
- Figures out what the version of the CodeFlare Operator csv currently is
- Uninstalls the subscription, csv and all the crds associated with the CodeFlare Operator
- Waits until the CodeFlare Operator pod is really gone
- Then it checks to ensure that the subscription, csv and the crds are really all gone
Using peak, and with an already installed codeflare operator, I've been running the test script with success.  Here's the test detail:
```
./run.sh 
++++++ /root/MICHAEL/distributed-workloads/peak/operator-tests/opendatahub-kubeflow/ …
```

E2E CodeFlare delete portion

---

tests/basictests/distributed-workloads.sh

This PR applies and deletes the  kfdef issues https://github.com/opendatahub-io/distributed-workloads/issues/16 and https://github.com/opendatahub-io/distributed-workloads/issues/19
It requires the CodeFlare Operator to already be installed, (which Kevin is taking care of in his PR #22
Then, my portion of the E2E test (section install_distributed_workloads_kfdef) does the following:
1.  Installs the kfdef
2. Makes sure the 3 expected pods (mcad-controller, instascale and kuberay operator) are running.  (NOTE - Once the KFDEF has Instascale as optional, or if we have two KFDEFs, then this test might need to be slighly modified to account for that.)
3. It makes sure the codeflare-nodebook imagestream is there
Then, my portion of the E2E test (section uninstall_distributed_workloads_kfdef) …

Adding kfdef add and delete

---

tests/resources/mcad-mnist-tests-Containerfile

Added Containerfile used to build image for testing MCAD job submission functionality. 
Depends on `mnist.py` in #31

add Containerfile for mcad mnist test

---

tests/basictests/distributed-workloads.sh

Unfortunately, I think due to the latest update of the ODH operator, the current check to ensure that the CodeFlare ] operator pod has been deleted is also catching the ODH operator and therefore the function never completes.
The change below, instead of checking for the CodeFlare Operator pod, it just checks now for the CodeFlare deployment, making sure that that has been removed before continuing.
Using the peak e2e method, I've been running the uninstall_codeflare_operator function and it's properly completing now:
```
./run.sh distributed-workloads.sh
...
Uninstalling Codeflare Operator
...
Running operator-tests/opendatahub-kubeflow/tests/basictests/distributed-workloads.sh:176: executing 'oc get deploy codeflare-operator-controller-manager -n openshift-operators' expecting any …
```

uninstall_codeflare_operator function has problem with pod deletion test

---

tests/resources/custom-nb-small.yaml
tests/resources/mnist_mcad_mini.ipynb
tests/resources/mnist_ray_mini.ipynb

Described in more detail in [issue 41](https://github.com/opendatahub-io/distributed-workloads/issues/41)
I found that the CodeFlare e2e test was struggling to complete on my Fyre OpenShift cluster within the 1200 second timeouts, and also couldn't complete within a "medium" Open Shift cluster (3 worker nodes with 16GB memory and 8 cpu each)
I change three files in this PR
1.  opendatahub-kubeflow/tests/resources/custom-nb-small.yaml
reducing the memory from 8Gi to 3Gi
2.  opendatahub-kubeflow/tests/resources/mnist_mcad_mini.ipynb
Increase the cpu for performance, but reduce the memory so it fits in a medium OC cluster.
3. opendatahub-kubeflow/tests/resources/mnist_ray_mini.ipynb
Increase the cpu for better performance
I'm running this PR on my OC 4.12.7 cluster and it's running well... …

CPU bump and memory decrease for custom notebook 

---

Quick-Start.md

The https://opendatahub.io website structure has been updated, and has broken some links.
I've checked the link works, and it's the only link to https://opendatahub.io in the repository.

fix(doc): Update link to ODH operator installation guide

---

ray/operator/base/kustomization.yaml

use opendatahub ray operator image to bypass dockerhub rate limiting

---

ray/operator/base/kustomization.yaml

We have accidentally been using the same configmap name for both CodeFlare and Ray. This hadn't been a problem with the old operator, but with the new operator, when users attempt to deploy only CodeFlare and not Ray (or the other way around), the ODH operator ends up in a reconcile loop where
CodeFlare creates cm -> Ray manifests say cm should be deleted, so operator deletes cm -> CodeFlare finds that the cm doesn't exist, so it creates again

Fix Ray generated configmap name

---

.mk/observability.mk
Makefile
Quick-Start.md
contrib/configuration/codeflare-operator-subscription.yaml
contrib/configuration/ndf-operator-subscription.yaml
contrib/configuration/nvidia-operator-subscription.yaml
contrib/configuration/opendatahub-operator-subscription.yaml

This PR adds a Makefile and the needed configuration files to quickly deploy the distribution stack into openshift. The Makefile includes `all-in-one` target to deploy all required components in a single command.
```
Usage:
make <target>
help                  Display this help.
all-in-one
all-in-one            Install distributed AI platform
general
install-opendatahub-operator  Install OpenDataHub operator
delete-opendatahub-operator  Delete OpenDataHub operator
install-codeflare-operator  Install CodeFlare operator
delete-codeflare-operator  Delete CodeFlare operator
CodeFlare
deploy-codeflare      Deploy CodeFlare
delete-codeflare      Delete CodeFlare
GPU Support
install-ndf-operator  Install NDF operator ( Node Feature Discovery )
delete-ndf-operator   Delete NDF operator …
```

adding makefile to deploy into openshift

---

tests/go.mod
tests/go.sum
tests/integration/ray_test.go

GetRayJobId call needs to be deferred to make sure that job id is stored by KubeRay cluster.
TestRayCluster test was failing on log storage line. Log storage function was deferred, however its arguments are resolved in realtime, causing GetRayJobId to be resolved before KubeRay operator had a chance to store job id in RayJob CR. 
Moving the whole log storage line into separate function makes sure that RayJob CR is fully initialized.
Manually.

Defer retrieving GetRayJobId in test

---

.github/workflows/tag-and-release.yml
README.md
tests/go.mod

Add GitHub Action for automatic release of ODH DW.
Fixes https://github.com/opendatahub-io/distributed-workloads/issues/59
The workflow updates release matrix, dependencies in tests and image stream.

Add GitHub Action for automatic release

---

Makefile

Add Makefile commands which allow installing CodeFlare operator from latest main branch.
This will come handy for ODH PR checks - making sure that PR is running against latest state of CodeFlare operator.
Commands clone main branch of CodeFlare operator repository and invoke `make deploy` to deploy latest operator.
Manually

Makefile: Add commands to install latest dev CodeFlare operator

---

Quick-Start.md

Closes #81 #95 
- Updated file paths to the guided demos based on changes made on this [PR and comment](https://github.com/project-codeflare/codeflare-sdk/pull/296#issuecomment-1673743770). 
- Updated dead links.
- Due to changing file paths to make use of a new demo, the quick-start tutorial needed to be adapted to reflect the changes.

Update file paths in Quick-Start

---

tests/integration/ray_test.go

Timeout which waits for 200 reply from dashboard route was added.
Fixes: https://github.com/red-hat-data-services/distributed-workloads/issues/5
- [*] The commits are squashed in a cohesive manner and have meaningful messages.
- [*] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [*] The developer has manually tested the changes and verified that the changes work

Fix the failing TestRayJobSubmissionRest test

---

Quick-Start-ODH-V2.md
Quick-Start.md

Fixes Issue https://github.com/opendatahub-io/distributed-workloads/issues/118
With the release of v0.2.3 of CodeFlare, the older names of the CRDs have changed, and the docs need to be adjusted to refer to the right crd names for cleanup.
I tested the cleanup steps on my OC 4.12 cluster and the CRDs were all deleted as expected:
oc delete crd instascales.codeflare.codeflare.dev mcads.codeflare.codeflare.dev quotasubtrees.quota.codeflare.dev appwrappers.workload.codeflare.dev schedulingspecs.workload.codeflare.dev
```
customresourcedefinition.apiextensions.k8s.io "instascales.codeflare.codeflare.dev" deleted
customresourcedefinition.apiextensions.k8s.io "mcads.codeflare.codeflare.dev" deleted
customresourcedefinition.apiextensions.k8s.io "quotasubtrees.quota.codeflare.dev" deleted …
```

CRD name changes require small tweak in the quickstart docs

---

README.md
ray/operator/base/params.env
ray/operator/crd/bases/ray.io_rayclusters.yaml
ray/operator/crd/bases/ray.io_rayjobs.yaml
ray/operator/crd/bases/ray.io_rayservices.yaml
ray/operator/rbac/leader_election_role.yaml
ray/operator/rbac/role.yaml

Upgrading the KubeRay from 0.5.0 to 0.6.0 and adjusting the readme, updating some of the underlying rbac and crd files to match the latest KubeRay Operator release.
- A new KubeRay operator image to 0.6.0
- Matching the latest crds from KubeRay 0.6.0
- Matching most of the latest RBAC's from KubeRay 0.6.0 (I left out the Multi-cluster items for now)
- Update to the ReadMe to change the mentioned release from 0.5.0 to 0.6.0
Testing by deploying from the CodeFlare Notebook with latest CodeFlare-SDK in my OpenShift 4.12 Cluster running ODH 1.9.0 and CodeFlare v0.2.3
```
oc get pods
NAME                                       READY   STATUS    RESTARTS   AGE
jobtest-head-zcq6z                         1/1     Running   0          7m
jobtest-worker-small-group-jobtest-5vcr8   1/1     Running   0 …
```

Upgrade KubeRay from 0.5.0 to 0.6.0

---

tests/go.mod
tests/go.sum
tests/integration/mcad_ray_test.go
tests/integration/pytorch_mcad_test.go
tests/integration/ray_test.go
tests/integration/resources/mnist.py
tests/integration/resources/mnist_mcad_mini.ipynb
tests/integration/resources/mnist_ray_mini.ipynb
tests/integration/resources/requirements.txt
tests/integration/sanity_test.go
tests/integration/support/config.go
tests/integration/support/net.go
tests/integration/support/notebook.go
tests/integration/support/odh.go
tests/integration/support/rbac.go
tests/integration/support/resources/custom-nb-small.yaml

Converting https://github.com/opendatahub-io/distributed-workloads/blob/e9ce41339e6158d6949e7fb55781647cb35f79da/tests/basictests/distributed-workloads.sh#L33-L90 into go lang integration tests.
As part of https://github.com/opendatahub-io/distributed-workloads/issues/63 this PR converts MNIST PyTorch test case into go lang.
Tested by executing locally against OCP.

Convert MNIST PyTorch and MNIST Ray test cases to go

---

Makefile
contrib/configuration/basic-dsc.yaml
contrib/configuration/opendatahub-operator-subscription.yaml

Adjusting Makefile commands to deploy ODH 2.x operator.
Fixes https://github.com/opendatahub-io/distributed-workloads/issues/121
Use ODH 2.x operator.
Added `contrib/configuration/basic-dsc.yaml`, this DSC CR will be used by OpenShift CI. Intention is to deploy basic ODH components using DSC CR, the rest is deployed manually to use latest resources (as done now).
Manually.

Makefile: Install ODH 2.x operator

---

codeflare-stack/rbac/mcad-controller-ray-clusterrolebinding.yaml

Fix a missing update from #125, to bind the Ray ClusterRole to the CodeFlare operator ServiceAccount.
It'll be simplified once project-codeflare/multi-cluster-app-dispatcher#635 is implemented.

Bind Ray ClusterRole to the new operator ServiceAccount

---

Quick-Start-ODH-V2.md
Quick-Start.md

Closes #137 
- Added info on GPU hardware discovery to both quickstarts.
- Previously the `all-in-one` make target has been updated to work for ODH v2.*. I moved this information from quickstartV1 to quickstartV2.
- **[Question]** Should I bring back the `all-in-one` make target specific to ODH v1?
Manual Test

Add info on GPU hardware discovery and updates to quickstarts

---

contrib/configuration/basic-dsc.yaml

Fix contextDir and sourcePath for ODH DSC used in PR checks
contextDir and sourcePath wasn't configured properly, causing PR check to leverage default manifest files instead of files from PR check.

Fix contextDir and sourcePath for ODH DSC used in PR checks

---

codeflare-stack/rbac/mcad-controller-ray-clusterrole.yaml

This PR follows up project-codeflare/codeflare-operator#316, and adds permissions on Routes, that's currently required by the SDK to expose the dashboard endpoints of provisioned Ray clusters.

Add Routes to Ray cluster role

---

tests/integration/ray_test.go

Closes #145 
This test was being blocked by this issue https://github.com/opendatahub-io/distributed-workloads/issues/65 which is now closed and merged.
The skip has been removed.

Enable ray_test

---

tests/integration/ray_test.go

It seems that busybox container is no longer needed.

Remove busybox container from tests

---

tests/integration/ray_test.go

Change assert to temporary fix the test for 2.4.

Temporary fix the test because of RHODS-12857

---

tests/integration/ray_test.go

It is because of RHODS-12857. Utilities which save the logs require RayJob status which may not be available.

Do not save logs when RayJob status is missing

---

model-images/bloom560m/Dockerfile
tests/kfto/config.json
tests/kfto/environment.go
tests/kfto/kfto_kueue_sft_test.go

This change allows to run e2e tests in disconnected environment, once all required images are provided.
Also it saves bandwidth by using available image to get a large model.
Model image currently hosted on my own Quay account, can be moved to dedicated account if we will decide which one.
Manually by running the e2e test.

Copy test model from image rather than downloading it

---

tests/kfto/core/kfto_kueue_sft_test.go
tests/kfto/upgrade/kfto_kueue_sft_upgrade_test.go

By default Kueue terminates Workload which isn't ready in 5 minutes.
As PyTorchJob image is big then Kueue may terminate job workload before image is pulled, causing test to fail.
By setting RestartPolicy to `OnFailure` the Kueue will restart PyTorchJob if it fails, making sure that wokload is processed on second attempt if first attempt fails pulling image.
Manually on a cluster without PyTorchJob image available on a node.

Restart PyTorchJob on failure to prevent Workload termination

---

examples/ray-finetune-llm-deepspeed/README.md
examples/ray-finetune-llm-deepspeed/ray_finetune_llm_deepspeed.ipynb
examples/ray-finetune-llm-deepspeed/requirements.txt
images/runtime/README.md
images/runtime/examples/README.md
images/runtime/examples/ray-torch/Dockerfile
images/runtime/ray/Dockerfile
images/runtime/ray/NGC-DL-CONTAINER-LICENSE
images/runtime/ray/README.md
images/runtime/ray/cuda.repo-arm64
images/runtime/ray/cuda.repo-x86_64

Provide a base Ray container image for Distributed Workloads, that includes the following layers / components:
* UBI 9
* Python 3.9
* CUDA 12.1
* Ray 2.23.0
Document how to build a custom container image on top of that base Ray container image. 
See https://issues.redhat.com/browse/RHOAIENG-7846 and https://issues.redhat.com/browse/RHOAIENG-7875.
This image has been successfully tested with the [ray-finetune-llm-deepspeed](https://github.com/opendatahub-io/distributed-workloads/tree/main/examples/ray-finetune-llm-deepspeed) example, by building a custom image on top of it, containing PyTorch 2.3.1, and fine-tuning Llama 7B model over several epochs (~10h run):
The Ray dashboard is working as expected, and GPU utilisation nominal:

UBI9 Ray container image

---

tests/odh/resources/requirements.txt

Latest pip is not able to install previous version.

Fix Pytorch lightning version

---

examples/ray-finetune-llm-deepspeed/ray_finetune_llm_deepspeed.ipynb

This PR updates the `ray-finetune-llm-deepspeed` to use the Ray base container image directly, instead of the custom PyTorch one.
This is possible since Flash Attention 2 is installed from wheel file directly, which does not require PyTorch to be pre-installed. 
I ran the `ray-finetune-llm-deepspeed` example.

Use Ray base container image in fine-tuning example

---

tests/odh/resources/mnist_hpo_raytune.ipynb

Test `TestMnistRayTuneHpoGpu` failing due to improper gpu configuration.
Removing Parameter`entrypoint_num_gpus`as mnist_hpo script executes in parallel and requires more GPUs for each iteration
- Installed latest RHOAI version on cluster with GPU enabled
- Run the test `go test -v ./tests/odh -run  TestMnistRayTuneHpoGpu`

Update HPO Ray Tune GPU test

---

go.mod
go.sum
tests/kfto/upgrade/kfto_kueue_sft_upgrade_training_test.go

When namespace is not found then PyTorch update tests should fail fast. The change is done in `codeflare-common`, here I just use latest `codeflare-common` version.
Also raised timeout to execute PyTorch test as it may take some time with latest image.
Manually by running PyTorch update tests against OCP.

Fail fast PyTorch update tests when namespace is not found

---

tests/kfto/core/config.json
tests/kfto/core/config_granite_20b_code_instruct.json
tests/kfto/core/config_granite_34b_code_instruct_lora.json
tests/kfto/core/config_llama2_13b_chat_hf.json
tests/kfto/core/config_llama2_13b_chat_hf_lora.json
tests/kfto/core/config_lora.json
tests/kfto/core/config_merlinite_7b.json
tests/kfto/core/config_meta_llama3_1_70b_lora.json
tests/kfto/core/config_meta_llama3_1_8b.json
tests/kfto/core/config_meta_llama3_70b_instruct_lora.json
tests/kfto/core/config_meta_llama3_8b_instruct.json
tests/kfto/core/config_mixtral_8x7b_instruct_v01.json
tests/kfto/core/config_mixtral_8x7b_v01.json

Parameter tokenizer_name_or_path should be used only in rare cases if user needs to provide custom tokenizer. By default the tokenizer is retrieved from the same path as model and all the needed tokens are provided.
Removing tokenizer_name_or_path parameter as it shouldn't be used unless there is some specific use case (no such use case in our tests for now).
Manually by running integration tests against OCP.

KFTO: Remove tokenizer_name_or_path parameters in tests

---

images/runtime/examples/ray-torch/Dockerfile
images/runtime/ray/Dockerfile
images/runtime/ray/Pipfile
images/runtime/ray/Pipfile.lock

This PR updates the Ray container images build to use `Pipefile.lock` files so it's reproducible. 
See https://issues.redhat.com/browse/RHOAIENG-11120.
I've successfully tested the [LLMs fine-tuning with Ray example](https://github.com/opendatahub-io/distributed-workloads/tree/main/examples/ray-finetune-llm-deepspeed) using images built with these changes.

Make Ray container image build reproducible

---

examples/stable-diffusion-dreambooth/yaml/operators/nvidia.yaml

Use stable channel instead of hard coded version. The current version does not work with the latest OCP 4.16.10. The nvidia driver can not compile with this error
```
+ make -s -j SYSSRC=/lib/modules/5.14.0-427.33.1.el9_4.x86_64/build nv-linux.o nv-modeset-linux.o
ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol '__rcu_read_unlock'
ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol '__rcu_read_lock'
make[2]: *** [scripts/Makefile.modpost:134: /usr/src/nvidia-535.104.05/kernel/Module.symvers] Error 1
make[2]: *** Deleting file '/usr/src/nvidia-535.104.05/kernel/Module.symvers'
make[1]: *** [Makefile:1850: modules] Error 2
make: *** [Makefile:82: modules] Error 2
++ make -s -j SYSSRC=/lib/modules/5.14.0-427.33.1.el9_4.x86_64/build clean
```
Change …

Use stable channel for Nvidia GPU operator

---

instructlab/standalone/README.md
instructlab/standalone/sdg-data-to-s3.py
instructlab/standalone/standalone.py

This PR adds the initial `standalone.py` script for running the [InstructLab](https://github.com/instructlab) process as a set of Kubernetes Jobs with distributed training (Kubeflow Training Operator).  Currently the script assumes valid SDG data exists in an S3 bucket and that their is an appropriate judge model endpoint available. Currently, the script will download the valid SDG data from S3, run phase 1 training, run phase 2 training, run mt_bench eval, run final eval, and then push the trained model back to an s3 bucket.
This PR also includes the current README.md as well as a helper script for pushing the correct data into S3.

Initial commit for instructlab standalone script

---

examples/ray-finetune-llm-deepspeed/README.md

Use newer SDK parameters in LLM fine-tuning job configurations

---

images/runtime/training/cuda/Dockerfile

Fixes the following issue with latest versions of the NVIDIA GPU operator: 
```
Error: container create failed: time="2024-11-12T14:03:56Z" level=error msg="runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: error parsing IMEX info: unsupported IMEX channel value: all\n" 
```

Add missing NVIDIA_REQUIRE_CUDA env variable to KFTO CUDA image

---

tests/kfto/core/environment.go
tests/kfto/core/hf_llm_training.py
tests/kfto/core/kfto_training_test.go

[RHOAIENG-14536](https://issues.redhat.com/browse/RHOAIENG-14536)
[RHOAIENG-14537](https://issues.redhat.com/browse/RHOAIENG-14537)
[RHOAIENG-14568](https://issues.redhat.com/browse/RHOAIENG-14568)
- Added an E2E test to cover usage of the CUDA and ROCm training images.
- Included a [python script taken from the training-operator](https://github.com/kubeflow/training-operator/blob/master/sdk/python/kubeflow/trainer/hf_llm_training.py) for which I have included the apache license and a reference to the location of the original script. I have noted in a comment where the script has been altered.
- Added environment variables so that the test can be used for both CUDA and ROCm images.
I have run the test with the CUDA image on a rosa cluster.  (Plan to test ROCm image next on AMD cluster.)

E2E tests for kfto pytorch image

---

tests/kfto/core/kfto_training_test.go
tests/kfto/core/support.go

This PR adjusts 'go.embed' to accept python files and removes the "ReadExt" method
Tested the changes manually by running the KFTO tests locally

Adjust 'go.embed' to accept python files

---

tests/kfto/core/hf_llm_training.py
tests/kfto/core/kfto_training_test.go

[RHOAIENG-16198](https://issues.redhat.com/browse/RHOAIENG-16198)
- Update test to utilise alpaca dataset image to access dataset instead of downloading it from huggingface
- Updated training script to use sequential dataset pre-processing instead of parallel to avoid MD5 hash checks
Same approach tested locally using data copied from [alpaca-dataset image](quay.io/ksuta/alpaca-dataset@sha256:2e90f631180c7b2c916f9569b914b336b612e8ae86efad82546adc5c9fcbbb8d) :

Update kfto test to utilise alpaca dataset image to access dataset instead of downloading it from huggingface

---

tests/kfto/core/support.go
tests/kfto/upgrade/kfto_kueue_sft_upgrade_training_test.go
tests/kfto/upgrade/kfto_sft_upgrade_sleep_test.go

These changes allows running setup tests multiple times without throwing an error.
The idempotency was implemented by using `applyconfiguration` for `ResourceFlavor` , `ClusterQueue` and `LocalQueue` CRs, namespace and PyTorchJob duplications are handled by dedicated code.
Manually by running on OCP.

Adjust KFTO PyTorchJob upgrade tests to be idempotent

---

images/dataset/alpaca/Dockerfile

Related to [RHOAIENG-16556](https://issues.redhat.com/browse/RHOAIENG-16556)
Generate a smaller dataset which is needed to execute KFTO training tests with CPU in limited time
Build locally and pushed the image to quay `quay.io/shchugh/alpaca-dataset?tab=tags&tag=amd64`

Generate a smaller dataset

---

.tekton/training-cuda-pull-request.yaml
.tekton/training-cuda-push.yaml
.tekton/training-rocm-pull-request.yaml
.tekton/training-rocm-push.yaml

Copy the latest versions of Konflux pipelines from downstream fork for the training images,  so changes can be applied here, as for the Ray images (see #242).

Upstream Konflux pipelines for training images

---

tests/kfto/kfto_mnist_training_test.go
tests/kfto/resources/mnist.py
tests/kfto/resources/requirements-rocm.txt
tests/kfto/resources/requirements.txt

Added MNIST test to run KFTO Multi-node distributed training using NVIDIA(CUDA) and AMD GPUs(ROCm)
[RHOAIENG-14540](https://issues.redhat.com/browse/RHOAIENG-14540)
[RHOAIENG-14541](https://issues.redhat.com/browse/RHOAIENG-14541)
```
export NOTEBOOK_IMAGE=quay.io/modh/odh-generic-data-science-notebook@sha256:7c1a4ca213b71d342a2d1366171304e469da06d5f15710fab5dd3ce013aa1b73 \
CODEFLARE_TEST_RAY_IMAGE=quay.io/rhoai/ray@sha256:b0e129cd2f4cdea7ad7a7859031357ffd9915410551f94fbcb942af2198cdf78    # CUDA image \
FMS_HF_TUNING_IMAGE=quay.io/modh/fms-hf-tuning@sha256:6f98907f9095db72932caa54094438eae742145f4b66c28d15887d5303ff1186
```
For running test using AMD GPUs, use ROCM image : `quay.io/modh/ray@sha256:db667df1bc437a7b0965e8031e905d3ab04b86390d764d120e05ea5a5c18d1b4`
```
go test -v …
```

Add MNIST test to run multi-node distributed training using KFTO

---

images/tests/Dockerfile

Creating a Dockerfile to build an image which will contain GoLang dependencies and the tests. Besides the dependencies defined in the go.mod, the dockerfile is adding `gotestsum` pkg (https://github.com/gotestyourself/gotestsum) which provides more features for running tests, like generation of junit reports needed for the integration with CI and reporting systems.
Note: setting the working directory to `distributed-workloads/tests` because `gotestsum` runs by default from the current directory (`./...`). Alternatively it is possible to set up the folder to run in 2 ways:
1. setting TEST_DIRECTORY env variable - _it seems to take always precedence_
2. using go test command (i.e., gotestsum -- ./tests) - _the syntax is not very comfortable_
However, both 1 and 2 poses issue when we want to …

Add Dockerfile for running tests in CI

---

.tekton/ray-rocm-push.yaml
images/runtime/ray/rocm/Dockerfile

Closes [RHOAIENG-16891](https://issues.redhat.com/browse/RHOAIENG-16891)
Upgrade AMD Ray runtime image to ROCm v6.2.4
Tested the changes by building the image locally and pushing to my quay repo and then successfully executed the `TestMnistRayROCmGpu` with the new image

Upgrade AMD Ray runtime image to ROCm v6.2.4

---

.tekton/training-rocm-push.yaml
images/runtime/training/rocm/Dockerfile
images/runtime/training/rocm/README.md

Closes [RHOAIENG-16892](https://issues.redhat.com/browse/RHOAIENG-16892)
Upgrade AMD Training operator runtime image to ROCm v6.2.4
Build the image locally and pushed to `https://quay.io/repository/shchugh/training?tab=tags&tag=kfto-rocm624` and then then successfully executed the KFTO tests with the new image

Upgrade AMD Training operator runtime image to ROCm v6.2.4

---

tests/kfto/kfto_training_test.go

The TestPyTorchJobSingleNodeSingleGpuWithCuda test is failing with timeout error which is the only test failing out of all Multi-node tests -
Compute resources used : 2* g4dn.xlarge
Test passed when updated the timeout time from 20 mins(TestTimeoutDouble) to 30mins(TestTimeoutGpuProvisioning)  here : :heavy_check_mark: 
https://github.com/opendatahub-io/distributed-workloads/blob/1445fa64c9643e78caaf76f653cebff7b1eb73eb/tests/kfto/kfto_training_test.go#L111

Update timeout time for the TestTimeoutGpuProvisioning test

---

tests/common/template.go

The duplicate parsing produce doubled training script, causing training delays and text replacing issues.
Manually by running `TestMnistRayCpu` on OCP.

e2e tests: Remove duplicate template parsing

---

examples/ray-finetune-llm-deepspeed/ray_finetune_llm_deepspeed.ipynb

Remove the assertion that checks if a S3 bucket is set as the example can be used with PVC as well.

Remove assertion if S3 bucket is missing and support PVC

---

images/runtime/training/cuda/Pipfile.lock

Follows #327 where native x86_64 libraries are missing from the pipenv lock file.

Fix missing x86_64 libraries in CUDA training image

---

images/runtime/training/rocm/Dockerfile

Add Flash Attention 2 to ROCm training image.
Successfully built and pushed at quay.io/astefanu/training@sha256:0485504d352c14d9009c44872921e8a87092c28f43a0ae8aa126885f9db95700

Add Flash Attention to ROCm training image

---

images/runtime/training/cuda/Pipfile
images/runtime/training/cuda/Pipfile.lock
images/runtime/training/rocm/Pipfile
images/runtime/training/rocm/Pipfile.lock

pull request adds TensorBoard import to both the CUDA and ROCm training images under distributed-workloads/images/runtime/training. It also updates TRL from version 0.15.1 to 0.15.2.
Tested via:
1. Built and pushed updated image to Quay.io repo
2. Validated on Openshift by running test jobs

Add tensorboard import

---

tests/fms/environment.go
tests/fms/kfto_kueue_sft_GPU_test.go
tests/fms/kfto_kueue_sft_test.go
tests/fms/resources/config.json
tests/fms/resources/config_lora.json
tests/fms/resources/config_qlora.json
tests/fms/support.go

From fms-hf-tuning 2.6.0 the training script isn't able to process existing bloom model.
So this PR upgrades fms tests to use granite-3b-code-base-2k model.
Another upgrade is to use GPU for training, which should speed up test execution time.
For disconnected environment the granite model can be downloaded from S3 bucket.

Adjust fms-hf-tuning tests to use granite-3b-code-base-2k model

---

images/runtime/training/rocm/Dockerfile
images/runtime/training/rocm/Pipfile
images/runtime/training/rocm/Pipfile.lock

Fixes the installation of the bitsandbytes package on ROCm.
Successfully tested with the LLM SFT Trainer example on 8x AMD Instinct MI300X:

Install BitsAndBytes from source in ROCm training image

---

examples/kfto-sft-llm/sft.ipynb

Use processing_class instead of deprecated tokenizer argument in SFTTrainer
Successfully ran the LLM fine-tuning example.

Use processing_class instead of deprecated tokenizer argument in SFTTrainer

---

examples/hpo-raytune/notebook/raytune-oai-MR-gRPC-demo.ipynb
examples/hpo-raytune/notebook/raytune-oai-demo-mlmd.ipynb
examples/hpo-raytune/notebook/raytune-oai-demo.ipynb
examples/ray-finetune-llm-deepspeed/ray_finetune_llm_deepspeed.ipynb
examples/stable-diffusion-dreambooth/notebook/00 Intro.ipynb

Added a comment to clarify the need to specify `rhods-notebooks` namespace in RayCluster config.
This is required to run the notebooks locally while leveraging a RHOAI cluster. Comment purely added for clarity.
Only change is the addition of a comment in demo notebooks which use `codeflare-sdk`.

task(RHOAIENG-14661): add comment to demo notebooks

---

images/runtime/training/cuda/Dockerfile

Run `fix-permissions` after installing `nvidia-nccl-cu12`.
It seems that `nvidia-nccl-cu12` mess with permissions, preventing package installations using PyTorchJob SDK.

Fix broken OpenShift permissisons for training CUDA image

---

images/runtime/training/py311-rocm62-torch251/Dockerfile

This PR updates the installation of Flash Attention 2 from source for the KFTO ROCm training image to comply with PEP-517.
I've successfully run the LLM fine-tuning with KFTO example with AMD accelerators using the pre-built `quay.io/astefanu/training:py311-rocm62-torch251-2` image.

Egg-based install is not supported anymore according to PEP-517

---

tests/odh/validating_admission_policy_test.go

Jira: https://issues.redhat.com/browse/RHOAIENG-19694 
ValidatingAdmissionPolicy PR: https://github.com/opendatahub-io/kueue/pull/76 
- Added VAP tests for `PyTorchJobs`.
- Added new AppWrapper test cases.
- Refactored the tests for readability and scalability.
This should be tested alongside this PR: https://github.com/opendatahub-io/kueue/pull/76 
1. Ensure OCP cluster is `>=v4.17`
2. Ensure Kueue, CodeFlare-Operator(and AppWrapper controller), KubeRay, and Training-Operator are installed.
3. Run `go test -timeout 1m ./tests/odh/validating_admission_policy_test.go ./tests/odh/support.go`.

Add VAP tests for PyTorchJobs

---

.github/workflows/snyk-dockerfile-scan.yml

Link to Issues:
https://issues.redhat.com/browse/RHOAIENG-23049
Adds a GitHub Actions workflow that runs Snyk container scans on every Dockerfile under
`images/runtime/training/'.
scan fails the PR if High/Critical CVEs exist in the base image.
if PR is succesfuly merged please integrate secret called: 
"SNYK_TOKEN"

Added Github actions for snyk scan

---

images/runtime/training/py311-rocm62-torch241/Dockerfile
images/runtime/training/py311-rocm62-torch251/Dockerfile

while trying to use latest kubeflow-training sdk version 1.9.2 to create pytorchjob after passing packages-to-install argument, below issue came up : 
```
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'libproton.so'
Check the permissions.
Traceback (most recent call last):
File "/tmp/tmp.R13JmiiOrT/ephemeral_script.py", line 147, in <module>
train_func()
File "/tmp/tmp.R13JmiiOrT/ephemeral_script.py", line 6, in train_func
from torchvision import datasets, transforms
ModuleNotFoundError: No module named 'torchvision
```
Re‑chmod and fix-permissions on /opt/app-root/lib/python3.11/site-packages in
a new layer so that newly installed shared libraries (e.g. libproton.so) are
writable by the non‑root container user.

Reapply site-packages permissions after installing pytorch-triton-rocm in ROCm dockerfiles

---

.github/workflows/build-and-push-test-images.yml
Makefile

Closes [RHOAIENG-18526](https://issues.redhat.com/browse/RHOAIENG-18526)
Add workflow to build and push test images to https://quay.io/repository/opendatahub/distributed-workloads-tests
Build and push the image via workflow in my [fork](https://github.com/ChughShilpa/distributed-workloads/actions/runs/15114366726)
can see latest image [here](https://quay.io/repository/shchugh/opendatahub/distributed-workloads-tests?tab=tags&tag=latest)

Add workflow to build and push test images

---

tests/common/support/defaults.go
tests/common/support/environment.go
tests/common/support/environment_test.go
tests/common/support/test.go
tests/kfto/kfto_kueue_mnist_upgrade_training_test.go
tests/kfto/kfto_mnist_sdk_test.go
tests/kfto/kfto_mnist_training_test.go
tests/kfto/kfto_pytorchjob_failed_test.go
tests/kfto/kfto_training_test.go

By deprecating downstream test we need to separate PyTorch 2.4.1 and PyTorch 2.5.1 tests in ODH, to be able to run them as part of one test run.
Manually by running sample tests.

Split e2e tests to dedicated PyTorch241 and PyTorch251
